### ISSUE TITLE
Configuration problems

### ISSUE THREAD

**Issue by moudyellaz** [verificatum/verificatum-vjsc#2]
Hi,

I am currently working on ElGamal Cryptosystem and would like to test your library. I ma having issues in ./configure after cloning your library.

Moreover, i tried vjsc.js file but still cannot use your functions.

Could you please provide me with a simple example on how to use ElGamal.

Best

**Comment by verificatum** [comment]
I am sorry, but I do not have time to provide examples right now.

Could you please be more specific about your configuration problem?
